### PR TITLE
Del twitter

### PR DESCRIPTION
**Pull request by crhan**

### CODE REVIEW

**Comment by crhan** [comment]
👍

**Comment by crhan** [comment]
:no_entry: PR rejected with a vote of 3 for and 0 against, a weighted total of 3.0 and a threshold of 1.0, and **NO** current meritocracy review.

Open a new PR to restart voting.

**Comment by crhan** [comment]
> /vote reopen

Command Ran

**Review by blueanne — APPROVED** [review]

**Comment by crhan** [comment]
:no_entry: PR rejected with a vote of 3 for and 0 against, a weighted total of 3.0 and a threshold of 1.0, and **NO** current meritocracy review.

Open a new PR to restart voting.

**Pull request closed without merging**
